
package com.cxf.server;

import javax.jws.WebMethod;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSCxfJAX", targetNamespace = "http://cxf.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSCxfJAX {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://cxf.com/", className = "com.cxf.server.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://cxf.com/", className = "com.cxf.server.SayHelloResponse")
    public void sayHello();

}
