
package com.cxf.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSCxfJAXServer", targetNamespace = "http://cxf.com/", wsdlLocation = "http://localhost:8888/ws?wsdl")
public class WSCxfJAXServer
    extends Service
{

    private final static URL WSCXFJAXSERVER_WSDL_LOCATION;
    private final static WebServiceException WSCXFJAXSERVER_EXCEPTION;
    private final static QName WSCXFJAXSERVER_QNAME = new QName("http://cxf.com/", "WSCxfJAXServer");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/ws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSCXFJAXSERVER_WSDL_LOCATION = url;
        WSCXFJAXSERVER_EXCEPTION = e;
    }

    public WSCxfJAXServer() {
        super(__getWsdlLocation(), WSCXFJAXSERVER_QNAME);
    }

    public WSCxfJAXServer(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSCXFJAXSERVER_QNAME, features);
    }

    public WSCxfJAXServer(URL wsdlLocation) {
        super(wsdlLocation, WSCXFJAXSERVER_QNAME);
    }

    public WSCxfJAXServer(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSCXFJAXSERVER_QNAME, features);
    }

    public WSCxfJAXServer(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSCxfJAXServer(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSCxfJAX
     */
    @WebEndpoint(name = "WSCxfJAXPort")
    public WSCxfJAX getWSCxfJAXPort() {
        return super.getPort(new QName("http://cxf.com/", "WSCxfJAXPort"), WSCxfJAX.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSCxfJAX
     */
    @WebEndpoint(name = "WSCxfJAXPort")
    public WSCxfJAX getWSCxfJAXPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://cxf.com/", "WSCxfJAXPort"), WSCxfJAX.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSCXFJAXSERVER_EXCEPTION!= null) {
            throw WSCXFJAXSERVER_EXCEPTION;
        }
        return WSCXFJAXSERVER_WSDL_LOCATION;
    }

}
