
package com.webService.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServiePublishService", targetNamespace = "http://publish.webService.com/", wsdlLocation = "http://192.168.0.104:6666/ws_2?WSDL")
public class WebServiePublishService
    extends Service
{

    private final static URL WEBSERVIEPUBLISHSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVIEPUBLISHSERVICE_EXCEPTION;
    private final static QName WEBSERVIEPUBLISHSERVICE_QNAME = new QName("http://publish.webService.com/", "WebServiePublishService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.0.104:6666/ws_2?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVIEPUBLISHSERVICE_WSDL_LOCATION = url;
        WEBSERVIEPUBLISHSERVICE_EXCEPTION = e;
    }

    public WebServiePublishService() {
        super(__getWsdlLocation(), WEBSERVIEPUBLISHSERVICE_QNAME);
    }

    public WebServiePublishService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVIEPUBLISHSERVICE_QNAME, features);
    }

    public WebServiePublishService(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVIEPUBLISHSERVICE_QNAME);
    }

    public WebServiePublishService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVIEPUBLISHSERVICE_QNAME, features);
    }

    public WebServiePublishService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiePublishService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServiePublish
     */
    @WebEndpoint(name = "WebServiePublishPort")
    public WebServiePublish getWebServiePublishPort() {
        return super.getPort(new QName("http://publish.webService.com/", "WebServiePublishPort"), WebServiePublish.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiePublish
     */
    @WebEndpoint(name = "WebServiePublishPort")
    public WebServiePublish getWebServiePublishPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://publish.webService.com/", "WebServiePublishPort"), WebServiePublish.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVIEPUBLISHSERVICE_EXCEPTION!= null) {
            throw WEBSERVIEPUBLISHSERVICE_EXCEPTION;
        }
        return WEBSERVIEPUBLISHSERVICE_WSDL_LOCATION;
    }

}
