
package com.webService.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiePublish", targetNamespace = "http://publish.webService.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiePublish {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://publish.webService.com/", className = "com.webService.client.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://publish.webService.com/", className = "com.webService.client.SayHelloResponse")
    @Action(input = "http://publish.webService.com/WebServiePublish/sayHelloRequest", output = "http://publish.webService.com/WebServiePublish/sayHelloResponse")
    public void sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
