
package com.cxf.server.impl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StudentServiceImpl", targetNamespace = "impl.server.cxf.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StudentServiceImpl {


    /**
     * 
     * @param id
     * @return
     *     returns java.util.List<com.cxf.server.impl.Student>
     */
    @WebMethod
    @WebResult(name = "student", targetNamespace = "")
    @RequestWrapper(localName = "find", targetNamespace = "impl.server.cxf.com", className = "com.cxf.server.impl.Find")
    @ResponseWrapper(localName = "findResponse", targetNamespace = "impl.server.cxf.com", className = "com.cxf.server.impl.FindResponse")
    public List<Student> find(
        @WebParam(name = "id", targetNamespace = "")
        int id);

}
