
package com.cxf.server.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StudentServiceImplServer", targetNamespace = "impl.server.cxf.com", wsdlLocation = "http://localhost:8888/cxf_spring/ws/student?wsdl")
public class StudentServiceImplServer
    extends Service
{

    private final static URL STUDENTSERVICEIMPLSERVER_WSDL_LOCATION;
    private final static WebServiceException STUDENTSERVICEIMPLSERVER_EXCEPTION;
    private final static QName STUDENTSERVICEIMPLSERVER_QNAME = new QName("impl.server.cxf.com", "StudentServiceImplServer");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/cxf_spring/ws/student?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STUDENTSERVICEIMPLSERVER_WSDL_LOCATION = url;
        STUDENTSERVICEIMPLSERVER_EXCEPTION = e;
    }

    public StudentServiceImplServer() {
        super(__getWsdlLocation(), STUDENTSERVICEIMPLSERVER_QNAME);
    }

    public StudentServiceImplServer(WebServiceFeature... features) {
        super(__getWsdlLocation(), STUDENTSERVICEIMPLSERVER_QNAME, features);
    }

    public StudentServiceImplServer(URL wsdlLocation) {
        super(wsdlLocation, STUDENTSERVICEIMPLSERVER_QNAME);
    }

    public StudentServiceImplServer(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STUDENTSERVICEIMPLSERVER_QNAME, features);
    }

    public StudentServiceImplServer(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentServiceImplServer(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StudentServiceImpl
     */
    @WebEndpoint(name = "StudentServiceImplPort")
    public StudentServiceImpl getStudentServiceImplPort() {
        return super.getPort(new QName("impl.server.cxf.com", "StudentServiceImplPort"), StudentServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StudentServiceImpl
     */
    @WebEndpoint(name = "StudentServiceImplPort")
    public StudentServiceImpl getStudentServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("impl.server.cxf.com", "StudentServiceImplPort"), StudentServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STUDENTSERVICEIMPLSERVER_EXCEPTION!= null) {
            throw STUDENTSERVICEIMPLSERVER_EXCEPTION;
        }
        return STUDENTSERVICEIMPLSERVER_WSDL_LOCATION;
    }

}
